---
- name: AWS EC2 Playbbok
  hosts: GitHubActionsKeyPair
  remote_user: ubuntu
  gather_facts: false
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        update_cache: true
        name:
          - nginx
        state: latest
    - name: Serving Custome File
      ansible.builtin.copy:
        src: ./index.html
        mode: "0644"
        dest: /var/www/html/index.html
      notify: Restart Nginx
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
