name: Ansible Deployment
on:
  workflow_dispatch:
  push:
jobs:
  ansible-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: AWS AuthN
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
