name: Ansible Deployment
on:
  workflow_dispatch:
  push:
jobs:
  ansible-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Layer
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            ~/.cache/
            ~/.ansible/
            /usr/lib/python3/dist-packages/
          key: ${{ runner.os }}-deps
      - name: Install Ansible
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: |
          pip3 install ansible boto3
      - name: Install amazon.aws Collection
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ansible-galaxy collection install amazon.aws
      - name: AWS AuthN
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Validate Inventory File
        run: |
          ansible-inventory --inventory inventory.aws_ec2.yaml --list
      - name: Write SSH Key Into File
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/myPrivKeyFile
          chmod 400 ~/myPrivKeyFile
      - name: Run Ansible Playbook
        run: |
          ansible-playbook --private-key ~/myPrivKeyFile ec2-playbook.yaml
