name: Ansible Deployment
on:
  workflow_dispatch:
  push:
jobs:
  ansible-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: |
            /usr/lib/python3/dist-packages/ansible_collections
            ~/.ansible/collections/ansible_collections
          key: ${{ runner.os }}-deps
      - name: Install Ansible
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: |
          sudo apt update && \
          sudo apt install --yes software-properties-common && \
          sudo add-apt-repository --yes --update ppa:ansible/ansible && \
          sudo apt install --yes ansible
      - name: Install amazon.aws Collection
        shell: bash
        run: |
          ansible-galaxy collection install amazon.aws
      # - name: AWS AuthN
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: us-east-1
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
